### ISSUE TITLE
No rates returned from version 0.1.3 to 0.1.6

### ISSUE THREAD

**Issue by dlaramee** [flagshipcompany/flagship-for-woocommerce#15]
I was testing with 0.1.1 lately, now upgraded to 0.1.6 and there is no rates returned, so woocommerce will simply display a message stating there is no delivery option for that area (or something similar).

I downgraded the version until it worked and the latest version that returned rates is 0.1.2

So 0.1.3 to 0.1.6 are not returning rates with my configuration.

**Comment by yi-FLS** [comment]
@dlaramee v0.1.6 is not backward compatible due to change in shipping record format. It means you may not be able to "create shipment" from existing order that were previously quoted. However, it should have set of returned rates. Can you provide a bit more details about your configuration (including php version).

**Comment by dlaramee** [comment]
True... It works with a new cart.
