### ISSUE TITLE
Plugin causes WooProducts to not be available

### ISSUE THREAD

**Issue by colormage** [flagshipcompany/flagship-for-woocommerce#17]
Thank you for creating this plugin that I have been waiting for
I hope I will be able to import the WooCommerce order info into Flagship to auto populate the recipients coordinates. The auto populate would be of greater use than the rates

I am getting this error
Upon activation this message is visible
**_Notice: Undefined index: setup.filters in /home/transff3/public_html/rubontransferecommerce/wp-content/plugins/flagship-for-woocommerce-0.1.10/includes/components/hook/class.flagship-hook.php on line 38 Notice: Undefined index: setup.actions in /home/transff3/public_html/rubontransferecommerce/wp-content/plugins/flagship-for-woocommerce-0.1.10/includes/components/hook/class.flagship-hook.php on line 38 Notice: Undefined index: metabox.actions in /home/transff3/public_html/rubontransferecommerce/wp-content/plugins/flagship-for-woocommerce-0.1.10/includes/components/hook/class.flagship-hook.php on line 38_**

No price is returned when selecting WooProducts with variations 
Sorry, this product is unavailable. Please choose a different combination.

once plugin is deactivated then all functions

Thank you

**Comment by yi-FLS** [comment]
@colormage currently, flagship-for-woocommerce plugin support live shipping rates quote available for any newly created order via store cart/checkout. For existing order, there exists a FlagShip metabox section that offers a "requote" option. Actual shipment / pick-up creation is also accessible from the same metabox. 

For the bug you experienced during plugin activation, it looks like that plugin is not properly initialized. But can you elaborate a bit of your woocomerce setup (version, relevant custom changes)?

For product variation problem, it seems to be rather an issue of the product setting. From What I understand, you need to set regular product price for each of your variation. Otherwise, it may not allow customer to add product into shopping cart. [here is a thread of similar problem](https://wordpress.org/support/topic/sorry-this-product-is-unavailable-please-choose-a-different-combination-err/)


Hope it'll help!

No price is returned when selecting WooProducts with variations
Sorry, this product is unavailable. Please choose a different combination.

**Comment by colormage** [comment]
Hi
See comments below under your comments

On 2016-09-03 11:54 PM, yi-FLS wrote:

@colormage<https://github.com/colormage> currently, flagship-for-woocommerce plugin support live shipping rates quote available for any newly created order via store cart/checkout. For existing order, there exists a FlagShip metabox section that offers a "requote" option. Actual shipment / pick-up creation is also accessible from the same metabox.

I understand live shipping rates but  the most important feature for me is that I can auto populate the clients destination info into the Flagship window to print the waybill without having to copy/pasted the clients ship to address
Will I be able to auto import or populate the destination address and info



For the bug you experienced during plugin activation, it looks like that plugin is not properly initialized. But can you elaborate a bit of your woocomerce setup (version, relevant custom changes)?

See attached system report for the details you requested

For product variation problem, it seems to be rather an issue of the product setting. From What I understand, you need to set regular product price for each of your variation. Otherwise, it may not allow customer to add product into shopping cart. here is a thread of similar problem<https://wordpress.org/support/topic/sorry-this-product-is-unavailable-please-choose-a-different-combination-err/>

All product variations have a regular price set, and returns a cost to the visitor as it has been doing so for a few years.
 It is only upon activation of the flagship plugin when the issue occurs and then returns to a functioning condition once the flagship plugin is deactivated

Could you create a separate plugin for the the auto populate of destination address on the flagship site as an alternative if the live rate plugin issue can not be corrected quickly or a disable live rates for those websites that may chose not to use it

Looking forward to hearing what the possibilties are

Glen



Hope it'll help!

No price is returned when selecting WooProducts with variations
Sorry, this product is unavailable. Please choose a different combination.

**Comment by patrick-fls** [comment]
Hi Glen,

The plugin is doing what you want, as it allows to confirm a shipment directly from the Order Page, as well as creating pickups. 
You don't need to go the shipping system to make a shipment (or copy paste the information).

We do not support WooCommerce 2.6 at the moment but we'll be working on that soon. you can keep an eye on that here: https://github.com/flagshipcompany/flagship-for-woocommerce/issues/18
