### ISSUE TITLE
Missing token / token error?

### ISSUE THREAD

**Issue by dlaramee** [flagshipcompany/flagship-for-woocommerce#24]
This is with 1.0.2

Frontend show:
```
FlagShip API Error:
Missing `x-smartship-token` header or could not find a valid token or your company is banned or disabled

Flagship Shipping has some difficulty in retrieving the rates. Please contact site administrator for assistance.
```

'Debug.log' show tons of these:
`[03-Oct-2016 14:05:47 UTC] PHP Notice:  Undefined index: enabled in /var/www/vhosts/website_url/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php on line 439`

Also, when activating the plugin, I had these in Debug:
```
[03-Oct-2016 13:53:02 UTC] PHP Notice:  Undefined index: enabled in /var/www/vhosts/website_url/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-shipping-method.php on line 439
[03-Oct-2016 13:53:10 UTC] PHP Notice:  Undefined property: FS\Context\ApplicationContext::$text_domain in /var/www/vhosts/website_url/wp-content/plugins/flagship-for-woocommerce/src/Components/Html.php on line 9

```
After activating the plugin and reading about the other issue reported by other users, I went to the settings and made sure to create a Shipping zone for Canada associated with Flagship.

And just to make sure, I went to the API Token website to make sure the token was active and reentered the token, again, just to make sure, and saved settings.... but no change.

**Comment by yi-FLS** [comment]
@dlaramee 
- for missing token problem: Due to WC's introduction of shipping zone, you need to fill shipping method settings per each shipping zone. i.e. go to Shipping -> Shipping Zones -> click on each of "FlagShip Shipping" link under the column "Shipping Method". Then you will have a form to fill.

- we are patching the 2nd bug which is i18n related. If you are using non-english as WP language you may need to upgrade to next minor release.

**Comment by dlaramee** [comment]
Missing token fixed.

And yes, I'm using french WP (actually bilingual with WPML) but default is french... 
Will wait for next minor release then ;)
