### ISSUE TITLE
Estimated Delivery Date

### ISSUE THREAD

**Issue by musiddiqui** [flagshipcompany/flagship-for-woocommerce#45]
Is there a way to add our shops processing time to the delivery date calculated by the flagship plugin in order to provide the customer with a more accurate delivery estimate?

Thanks.

**Comment by luis709394** [comment]
Thank you for pointing this out! We are working on it to find a better solution.

**Comment by luis709394** [comment]
Since different customers have different needs for the transit time that might or might not be shown in the shopping cart, it is difficult for us to come up with a solution for "adding extra days" to the transit time. What we did in our latest release (2.0.10) is adding a checkbox in the our plugin settings in each shipping zone. If the "show transit time" checkbox is checked, transit time for each shipping service will be shown. Otherwise, transit time will not be shown. Hopefully this new feature can work better for your team.
