### ISSUE TITLE
Unable to retrieve shipping level and rates

### ISSUE THREAD

**Issue by emizen28** [flagshipcompany/flagship-for-woocommerce#46]
Plugin is unable to retrieve any shipping level and cost. Also getting following error message:-
Notice: Undefined index: in .............../wp-content/plugins/flagship-for-woocommerce-2.0.9-prod/src/Components/Shipping/RateProcessor/EnabledRateProcessor.php on line 35
Please help me.
Thanks!

**Comment by luis709394** [comment]
But did you make sure that inside the shipping zone, some essential options are checked? If you go to woocommerce - settings - shipping - shipping zones, and pick a zone, you should see the first checkboxes checked like this

![screen shot 2018-10-05 at 12 23 01 pm](https://user-images.githubusercontent.com/8826928/46547901-74364580-c89b-11e8-8ba7-f5613de4ee2c.png)

So that it shows standard rates, express rates, and overnight rates.

If it still does not work, please let us know.
